/* BUNDLEGAME — styles (injected once; scoped under .bg-root) */
var BUNDLEGAME_CSS = [
  '.bg-root{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;max-width:820px;margin:0 auto;text-align:left;color:#111}',
  '.bg-root *{box-sizing:border-box}',
  '.bg-hud{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 14px}',
  '.bg-chip{background:#f1f5f9;border-radius:999px;padding:4px 12px;font-size:13px;font-weight:600}',
  '.bg-chip.bg-clock{background:#fef3c7}',
  '.bg-h{margin:0 0 10px;font-size:18px}',
  '.bg-muted{color:#64748b;font-size:13px}',
  '.bg-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px}',
  '.bg-card{border:2px solid #e2e8f0;border-radius:10px;padding:10px;cursor:pointer;background:#fff;transition:border-color .12s}',
  '.bg-card:hover{border-color:#cbd5e1}',
  '.bg-card.sel{border-color:var(--bg-accent);background:#eff6ff}',
  '.bg-card.dis{opacity:.45;cursor:not-allowed}',
  '.bg-card-h{display:flex;justify-content:space-between;align-items:baseline;gap:8px;margin-bottom:6px}',
  '.bg-items{display:flex;flex-wrap:wrap;gap:6px;margin:6px 0}',
  '.bg-item{display:flex;align-items:center;gap:4px;background:#f8fafc;border-radius:6px;padding:2px 6px;font-size:12px}',
  '.bg-emoji{font-size:15px}.bg-img{width:18px;height:18px;object-fit:cover;border-radius:3px}',
  '.bg-rec{background:#ecfdf5;border:1px solid #6ee7b7;border-radius:8px;padding:8px 10px;margin-bottom:10px;font-size:14px}',
  '.bg-actions{display:flex;gap:8px;margin-top:14px;flex-wrap:wrap}',
  '.bg-btn{background:var(--bg-accent);color:#fff;border:0;border-radius:8px;padding:9px 16px;font-size:14px;font-weight:600;cursor:pointer}',
  '.bg-btn:disabled{opacity:.4;cursor:not-allowed}',
  '.bg-btn.ghost{background:#fff;color:#334155;border:1px solid #cbd5e1}',
  '.bg-btn.sm{padding:5px 11px;font-size:13px}',
  '.bg-store{display:inline-block;border:1px solid #e2e8f0;border-radius:10px;padding:6px;background:#fff;margin-bottom:12px}',
  '.bg-row{display:flex}',
  '.bg-cell{width:74px;height:64px;margin:3px;border:1px solid #e2e8f0;border-radius:8px;background:#f8fafc;cursor:pointer;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;font-size:11px}',
  '.bg-cell.here{border-color:var(--bg-accent);background:#dbeafe;box-shadow:0 0 0 2px #bfdbfe}',
  '.bg-cell.empty{background:#fff;border-style:dashed;cursor:default}',
  '.bg-cell.static{cursor:default}',
  '.bg-cell-t{font-size:10px;color:#475569}',
  '.bg-walk{background:#fef3c7;border-radius:8px;padding:8px 12px;margin-bottom:10px;font-weight:600;font-size:14px}',
  '.bg-entry{display:flex;flex-direction:column;gap:8px;margin-bottom:14px}',
  '.bg-in{border:1px solid #cbd5e1;border-radius:7px;padding:7px 10px;font-size:14px;max-width:240px}',
  '.bg-in.qty{max-width:72px}',
  '.bg-qtys{display:flex;gap:10px;flex-wrap:wrap}',
  '.bg-qty{display:flex;flex-direction:column;gap:3px;font-size:12px;color:#475569}',
  '.bg-bags{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}',
  '.bg-bag{border:1px solid #e2e8f0;border-radius:9px;padding:9px;background:#fff}',
  '.bg-bagline{display:flex;justify-content:space-between;align-items:center;font-size:13px;padding:2px 0}',
  '.bg-x{border:0;background:#fee2e2;color:#b91c1c;border-radius:5px;cursor:pointer;padding:1px 7px;font-size:12px}',
  '.bg-del{display:flex;justify-content:space-between;align-items:center;gap:10px;border:1px solid #e2e8f0;border-radius:9px;padding:10px;margin-bottom:8px;background:#fff}',
  '.bg-del.done{background:#f0fdf4;border-color:#86efac}',
  '.bg-modal{position:fixed;inset:0;background:rgba(15,23,42,.55);display:flex;align-items:center;justify-content:center;z-index:9999}',
  '.bg-chip.bg-tut{background:#fae8ff;color:#86198f}',
  '.bg-steps{margin:0 0 14px;padding-left:20px}',
  '.bg-step{margin:5px 0;font-size:14px;line-height:1.45}',
  '.bg-modal-in{background:#fff;border-radius:12px;padding:18px;max-height:88vh;overflow:auto}'
].join('');
